//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OCine.BAL.Entity;

namespace Ocine.DAL.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using OCine.Common.CommonRepository.Interface;
    
    public partial class OcineDbEntities : DbContext, IUnitOfWork
    {
        public OcineDbEntities()
            : base("name=OcineDbEntities")
        {
           
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbContext Db => this;
        public DbContextTransaction StartTransaction()
        {
            return this.Db.Database.BeginTransaction();
        }

        public new int SaveChanges()
        {
            return this.Db.SaveChanges();
        }
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Cinema> Cinema { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Premiere> Premiere { get; set; }
        public virtual DbSet<Seances> Seances { get; set; }
        public virtual DbSet<User> User { get; set; }
        
    }
}
